services:
  database:
    image: 'mysql:8.0.40'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: roosh
      MYSQL_USER: roosh
      MYSQL_PASSWORD: roosh
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - roosh-shared-network
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1" ]
      interval: 5s
      timeout: 3s
      retries: 30

  web:
    build:
      context: ..
      dockerfile: docker-roosh-api/web/Dockerfile
    env_file: ../.env
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ..:/app
    networks:
      - roosh-shared-network

volumes:
  db-data:

networks:
  roosh-shared-network:
    external: true
